config/routes.rb
Giftbo::Application.routes.draw do
  get "home/index"

  resources :girltypes

  resources :colors

  resources :types

  resources :surveys do
    collection do
      get 'gift_list'
      get 'purchase_complete'
    end
  end

  resources :users

  root :to => 'home#index'

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :user 
  has_and_belongs_to_many :girltypes
  has_and_belongs_to_many :colors
  attr_accessible :anniversary_date, :budget, :dislikes, :dob, :flowers, :name, :phone_num, :ship_address, :ship_city, :ship_zip, :user, :zip
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all

    respond_to do |format|
      format.html # index.html.erb
      # format.json { render json: @surveys }
    end
  end
  
  def gift_list
    respond_to do |format|
      format.html # show.html.erb
      # format.json { render json: @survey }
    end
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @survey = Survey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      # format.json { render json: @survey }
    end
  end

  # GET /surveys/new
  # GET /surveys/new.json
  def new
    @survey = Survey.new

    respond_to do |format|
      format.html # new.html.erb
      # format.json { render json: @survey }
    end
  end

  # GET /surveys/1/edit
  def edit
    @survey = Survey.find(params[:id])
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(params[:survey])

    respond_to do |format|
      if @survey.save
        format.html { redirect_to :action => "gift_list", notice: 'Survey was successfully created.' }
        # format.json { render json: @survey, status: :created, location: @survey }
      else
        format.html { render action: "new" }
        # format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /surveys/1
  # PUT /surveys/1.json
  def update
    @survey = Survey.find(params[:id])

    respond_to do |format|
      if @survey.update_attributes(params[:survey])
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        # format.json { head :no_content }
      else
        format.html { render action: "edit" }
        # format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url }
      # format.json { head :no_content }
    end
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<style>
	textarea {
		rows:10;
	}
</style>
<%= form_for @survey, :html => {:class => "form-horizontal" } do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, "Her Name", :class => "control-label" %>
    <div class="controls"><%= f.text_field :name %></div>
  </div>
  <div class="control-group">
    <%= f.label :zip , "Her Zip Code", :class => "control-label" %>
    <div class="controls"><%= f.text_field :zip %></div>
  </div>
  <div class="control-group">
    <%= f.label :dob, "Her Date of Birth", :class => "control-label" %>
    <div class="controls"><%= f.date_select :dob, :start_year => 1975, :html_options => {:class => "input-small"} %></div>
  </div>
  <div class="control-group">
    <%= f.label :flowers, "Describe her personality using up to 10 keywords", :class => "control-label" %>
    <div class="controls"><%= f.text_area :flowers, :class => "wide-control", :rows => "10" %></div>
  </div>
  <div class="control-group">
    <%= f.label :anniversary_date, :class => "control-label" %>
    <div class="controls"><%= f.date_select :anniversary_date %></div>
  </div>
  <div class="control-group">
    <%= f.label :dislikes, "Her Dislikes", :class => "control-label" %>
    <div class="controls"><%= f.text_field :dislikes %></div>
  </div>
  <div class="control-group">
    <%= f.label :budget, "Your Budget",:class => "control-label" %>
    <div class="controls"><%= f.text_field :budget %></div>
  </div>
  <div class="control-group">
    <%= f.label :ship_address, :class => "control-label" %>
    <div class="controls"><%= f.text_field :ship_address %></div>
  </div>
  <div class="control-group">
    <%= f.label :ship_zip, :class => "control-label" %>
    <div class="controls"><%= f.text_field :ship_zip %></div>
  </div>
  <div class="control-group">
    <%= f.label :ship_city, :class => "control-label" %>
    <div class="controls"><%= f.text_field :ship_city %></div>
  </div>
  <%# <div class="control-group"> %>
  <%#   <%= f.label :phone_num, "Her Phone Number", :class => "control-label" %1> %>
  <%#   <div class="controls"><%= f.text_field :phone_num %1></div> %>
  <%# </div> %>
  <div class="actions pull-right">
    <%= f.submit 'Submit', :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/gift_list.html.erb
<div class="giftlistbox" style="width:1000;">
  <p style="padding-top:5px;">Your selections are ready<br />
  Gift List - Hipster</p>
</div>

<div id="myCarousel" class="carousel slide span6 offset3">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item giftlist">
	<p>Category : Experience</p>
	<img src="/assets/boniver640.jpg">
	<div class="carousel-caption">
		<h4>Bon Iver Tickets</h4>
		<p>$70.50</p>
		<a class="btn pull-right" href="purchase_complete">Order</a>
	</div>
    </div>
    <div class="item giftlist">
	<p>Category : Products</p>
	<img src="/assets/record640.jpg">
        <div class="carousel-caption">
                <h4>Retro Record Player</h4>
                <p>$66.99</p>
                <a class="btn pull-right" href="purchase_complete">Order</a>
        </div>

    </div>
    <div class="item giftlist">
	<p>Category : Jewelry</p>
	<img src="/assets/necklace640.jpg">
        <div class="carousel-caption">
                <h4>Vintage Camera Necklace</h4>
                <p>$59.99</p>
                <a class="btn pull-right" href="purchase_complete">Order</a>
        </div>
    </div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

<div class="giftlistbox" style="width:1000; float:left; min-height:1px;"></div>

app/views/surveys/index.html.erb
<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<style>
	#survey_flowers {
		rows:20;
	}
</style>
<div class="row"><div class="span10 offset1"><h3>Answer the following questions to find the perfect gift</h3>

<%= render 'form' %>
</div>
</div>

app/views/surveys/purchase_complete.html.erb
<div class="giftlistbox" style="width:1000px;">
  <p style="padding-top:12px;">Thank you! :)</p>
</div>
<p class="text-center" >Thank you for your purchase.</p>

<div class="giftlistbox" style="width:1000px; float:left; min-height:1px;">
</div>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @survey.name %>
</p>

<p>
  <b>Zip:</b>
  <%= @survey.zip %>
</p>

<p>
  <b>Dob:</b>
  <%= @survey.dob %>
</p>

<p>
  <b>Flowers:</b>
  <%= @survey.flowers %>
</p>

<p>
  <b>Anniversary date:</b>
  <%= @survey.anniversary_date %>
</p>

<p>
  <b>Dislikes:</b>
  <%= @survey.dislikes %>
</p>

<p>
  <b>Budget:</b>
  <%= @survey.budget %>
</p>

<p>
  <b>Ship address:</b>
  <%= @survey.ship_address %>
</p>

<p>
  <b>Ship zip:</b>
  <%= @survey.ship_zip %>
</p>

<p>
  <b>Ship city:</b>
  <%= @survey.ship_city %>
</p>

<p>
  <b>Phone num:</b>
  <%= @survey.phone_num %>
</p>

<p>
  <b>User:</b>
  <%= @survey.user %>
</p>


<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>