config/routes.rb
Giftbo::Application.routes.draw do
  get "home/index"

  resources :girltypes

  resources :colors

  resources :types

  resources :surveys do
    collection do
      get 'gift_list'
      get 'purchase_complete'
    end
  end

  resources :users

  root :to => 'home#index'

end

app/controllers/girltypes_controller.rb
class GirltypesController < ApplicationController
  # GET /girltypes
  # GET /girltypes.json
  def index
    @girltypes = Girltype.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @girltypes }
    end
  end

  # GET /girltypes/1
  # GET /girltypes/1.json
  def show
    @girltype = Girltype.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @girltype }
    end
  end

  # GET /girltypes/new
  # GET /girltypes/new.json
  def new
    @girltype = Girltype.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @girltype }
    end
  end

  # GET /girltypes/1/edit
  def edit
    @girltype = Girltype.find(params[:id])
  end

  # POST /girltypes
  # POST /girltypes.json
  def create
    @girltype = Girltype.new(params[:girltype])

    respond_to do |format|
      if @girltype.save
        format.html { redirect_to @girltype, notice: 'Girltype was successfully created.' }
        format.json { render json: @girltype, status: :created, location: @girltype }
      else
        format.html { render action: "new" }
        format.json { render json: @girltype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /girltypes/1
  # PUT /girltypes/1.json
  def update
    @girltype = Girltype.find(params[:id])

    respond_to do |format|
      if @girltype.update_attributes(params[:girltype])
        format.html { redirect_to @girltype, notice: 'Girltype was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @girltype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /girltypes/1
  # DELETE /girltypes/1.json
  def destroy
    @girltype = Girltype.find(params[:id])
    @girltype.destroy

    respond_to do |format|
      format.html { redirect_to girltypes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/girltypes_helper.rb
module GirltypesHelper
end

app/views/girltypes/_form.html.erb
<%= form_for(@girltype) do |f| %>
  <% if @girltype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@girltype.errors.count, "error") %> prohibited this girltype from being saved:</h2>

      <ul>
      <% @girltype.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/girltypes/edit.html.erb
<h1>Editing girltype</h1>

<%= render 'form' %>

<%= link_to 'Show', @girltype %> |
<%= link_to 'Back', girltypes_path %>

app/views/girltypes/index.html.erb
<h1>Listing girltypes</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @girltypes.each do |girltype| %>
  <tr>
    <td><%= girltype.name %></td>
    <td><%= link_to 'Show', girltype %></td>
    <td><%= link_to 'Edit', edit_girltype_path(girltype) %></td>
    <td><%= link_to 'Destroy', girltype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Girltype', new_girltype_path %>

app/views/girltypes/new.html.erb
<h1>New girltype</h1>

<%= render 'form' %>

<%= link_to 'Back', girltypes_path %>

app/views/girltypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @girltype.name %>
</p>


<%= link_to 'Edit', edit_girltype_path(@girltype) %> |
<%= link_to 'Back', girltypes_path %>